import { useEffect } from "react";
import { ArrowUpRight, FileText, ShieldCheck } from "lucide-react";
import Footer from "../components/landing/Footer";

const UPDATED_AT = "May 28, 2026";
const COMPANY_NAME = "W7S LLC";

const CLOUDFLARE_REFERENCES = [
  {
    label: "Cloudflare Self-Serve Subscription Agreement",
    href: "https://www.cloudflare.com/terms/",
  },
  {
    label: "Cloudflare Service-Specific Terms",
    href: "https://www.cloudflare.com/service-specific-terms-application-services/",
  },
  {
    label: "Cloudflare for Platforms documentation",
    href: "https://developers.cloudflare.com/cloudflare-for-platforms/",
  },
  {
    label: "Cloudflare Workers for Platforms documentation",
    href: "https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/",
  },
];

const CLOUDFLARE_PRIVACY_REFERENCES = [
  {
    label: "Cloudflare Privacy Policy",
    href: "https://www.cloudflare.com/privacypolicy/",
  },
  {
    label: "Cloudflare Data Processing Addendum",
    href: "https://www.cloudflare.com/cloudflare-customer-dpa/",
  },
  ...CLOUDFLARE_REFERENCES,
];

const TERMS_SECTIONS = [
  {
    title: "1. Agreement to these terms",
    body: [
      `${COMPANY_NAME} operates w7s.io, w7s.cloud, and the hosted W7S services. These Terms of Service govern access to W7S websites, documentation, hosted deployment endpoints, APIs, GitHub Actions integrations, and related services. By using W7S, you agree to these terms.`,
      "If you use W7S for a company or organization, you represent that you have authority to bind that organization. If you do not agree to these terms, do not use the hosted W7S services.",
    ],
  },
  {
    title: "2. What W7S provides",
    body: [
      "W7S is an open source deployment platform for GitHub-native applications. Hosted W7S deployments receive build output from GitHub Actions, verify the GitHub workflow context, and serve the deployed app from a public URL.",
      "The open source W7S code may be self-hosted under its applicable open source license. These terms do not limit rights granted by open source licenses, but they do govern hosted W7S services operated for the public W7S cloud.",
    ],
  },
  {
    title: "3. Your repositories, deployments, and content",
    body: [
      "You retain ownership of code, files, configuration, logs, deploy artifacts, custom domain declarations, and other content that you submit to W7S.",
      "You grant W7S a limited, worldwide, non-exclusive license to receive, copy, store, cache, route, execute, secure, analyze, and serve that content only as needed to provide, protect, measure, debug, and improve the service.",
      "You are responsible for your applications, public URLs, dependencies, secrets, configuration, user data, and compliance obligations. Do not deploy content that you do not have the right to deploy.",
    ],
  },
  {
    title: "4. GitHub Actions and credentials",
    body: [
      "W7S is designed to work from GitHub Actions. The W7S deploy action may receive repository metadata, workflow metadata, commit information, branch information, deploy archives, and the GitHub token or token-derived proof required to verify a deployment.",
      "You are responsible for controlling repository access, rotating secrets, reviewing workflow files, and ensuring that the GitHub account or organization authorizes the deployment.",
    ],
  },
  {
    title: "5. Acceptable use",
    body: [
      "You may not use W7S to host, distribute, or support malware, phishing, spam, credential theft, illegal content, harassment, intellectual property infringement, abusive automation, denial-of-service activity, unauthorized scanning, crypto mining, deceptive redirects, or attempts to bypass platform limits.",
      "You may not interfere with W7S, other users, infrastructure providers, or public networks. W7S may throttle, suspend, remove, or block deployments that create security, legal, abuse, reliability, or cost-control risk.",
    ],
  },
  {
    title: "6. Service limits, availability, and changes",
    body: [
      "Hosted W7S deployments are provided with published limits, abuse controls, and usage controls. Community and free hosted use may be limited, changed, suspended, or discontinued to keep the service available.",
      "W7S may change features, APIs, limits, pricing, routing behavior, or infrastructure as the platform evolves. W7S will try to avoid breaking documented workflows without notice, but urgent security or reliability changes may happen immediately.",
    ],
  },
  {
    title: "7. Billing",
    body: [
      "Hosted usage may be free, metered, or paid according to the pricing page, an order form, or another written agreement. You are responsible for charges, taxes, and usage generated by repositories or organizations you authorize.",
      "If billing is enabled for an account or organization, W7S may use payment processors and billing providers to process payments and manage invoices. Payment provider terms may also apply.",
    ],
  },
  {
    title: "8. Security and sensitive data",
    body: [
      "W7S uses reasonable technical and organizational measures to protect the service. No hosted platform can guarantee perfect security or uninterrupted operation.",
      "Do not send regulated sensitive data, payment card data, health data, government identifiers, or other high-risk personal data to community hosted deployments unless W7S has explicitly agreed in writing to support that use case.",
      "You should keep independent backups of source code, deploy artifacts, databases, and configuration that matter to your application.",
    ],
  },
  {
    title: "9. Third-party and upstream provider terms",
    body: [
      "W7S depends on third-party services such as GitHub, DNS providers, analytics providers, payment processors, infrastructure providers, and other integrations. Their terms, privacy policies, service-specific terms, acceptable use restrictions, platform limits, and abuse controls may apply to your use of W7S.",
      "Hosted W7S services use Cloudflare infrastructure and platform services, including products used for programmable hosting, routing, storage, security, observability, and network delivery. You may not use W7S in a way that violates Cloudflare terms or policies that apply to the underlying infrastructure W7S uses.",
      "If upstream provider terms, abuse controls, sanctions restrictions, data-processing obligations, or service limits require W7S to reject, throttle, suspend, remove, block, report, or modify a deployment, W7S may do so without liability.",
      "W7S is not responsible for third-party services that it does not control.",
    ],
    links: CLOUDFLARE_REFERENCES,
  },
  {
    title: "10. Disclaimers and liability",
    body: [
      "W7S is provided as is and as available. To the fullest extent allowed by law, W7S disclaims implied warranties, including warranties of merchantability, fitness for a particular purpose, non-infringement, and uninterrupted availability.",
      "To the fullest extent allowed by law, W7S will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for lost profits, lost revenue, lost data, or business interruption. W7S aggregate liability for hosted services is limited to the greater of USD 100 or the amount you paid to W7S for the affected hosted service in the six months before the event giving rise to the claim.",
    ],
  },
  {
    title: "11. Termination",
    body: [
      "You may stop using W7S at any time. W7S may suspend or terminate access to hosted services if you violate these terms, create risk for the service, exceed limits, fail to pay applicable charges, or use the service in a harmful or unlawful way.",
      "After termination, W7S may delete deployments, artifacts, logs, and account-related data according to operational retention practices and legal obligations.",
    ],
  },
  {
    title: "12. Updates and contact",
    body: [
      "W7S may update these terms from time to time. The updated date above shows when this page was last changed. Continued use of W7S after an update means you accept the updated terms.",
      "Questions about these terms can be sent to legal@w7s.io.",
    ],
  },
];

const PRIVACY_SECTIONS = [
  {
    title: "1. Scope",
    body: [
      `This Privacy Policy explains how ${COMPANY_NAME} collects and uses information when you visit w7s.io, read the documentation, use hosted W7S deployment services on w7s.cloud, call W7S APIs, or deploy through the W7S GitHub Action.`,
      "If you self-host W7S on infrastructure you control, W7S does not receive that self-hosted deployment data unless you separately send it to a hosted W7S service.",
    ],
  },
  {
    title: "2. Information W7S collects",
    body: [
      "Website and docs data: page views, referrers, browser and device details, approximate location derived from IP address, interaction data, cookies, and similar analytics information.",
      "GitHub and deployment data: repository owner, repository name, branch, commit SHA, workflow run metadata, GitHub token verification data, deploy archive metadata, custom domain declarations, configuration files, and generated deployment URLs.",
      "Runtime and operational data: request paths, status codes, timestamps, region or edge metadata, IP addresses, user agents, performance timings, error data, usage counters, bandwidth, storage, worker execution metrics, application logs, and abuse-prevention signals.",
      "Billing and contact data: email address, organization details, invoice data, and payment processor references if you use paid hosted features.",
    ],
  },
  {
    title: "3. How W7S uses information",
    body: [
      "W7S uses information to authenticate deploys, receive and serve applications, route custom domains, provide public URLs, calculate usage, enforce limits, detect abuse, debug failures, improve reliability, secure the platform, provide support, communicate service changes, and process billing where applicable.",
      "W7S does not sell your code, deploy artifacts, or personal information. W7S does not use your code, deploy artifacts, prompts, logs, or app content to train AI models unless you explicitly opt in or enter into a separate written agreement.",
    ],
  },
  {
    title: "4. Customer app data",
    body: [
      "Applications deployed on W7S may collect data from their own end users. The developer or organization that deploys the application is responsible for that application, its privacy notices, and its compliance obligations.",
      "W7S processes customer app traffic and logs only as needed to operate, secure, route, debug, measure, and enforce limits for hosted deployments.",
    ],
  },
  {
    title: "5. Cookies and analytics",
    body: [
      "W7S websites may use cookies, local storage, analytics tools, and session analytics to understand site usage and improve the product. Analytics may include page interactions and technical details about the browser session.",
      "You can control cookies through your browser settings. Blocking cookies may affect some features, but the documentation and public landing pages should generally remain readable.",
    ],
  },
  {
    title: "6. Sharing and subprocessors",
    body: [
      "W7S may share information with service providers that help operate the platform, including hosting and infrastructure providers, GitHub, analytics providers, support tools, billing providers, payment processors, abuse-prevention tools, and professional advisors.",
      "Hosted W7S services use Cloudflare as an infrastructure provider for routing, network delivery, programmable compute, storage, security, observability, and related platform operations. Cloudflare may process end-user traffic, IP addresses, request metadata, logs, network data, deploy artifacts, and other customer content as needed to provide those underlying services to W7S.",
      "Cloudflare privacy, data-processing, and service terms may apply to Cloudflare's processing as an infrastructure provider or subprocessor.",
      "W7S may also disclose information when required by law, to protect users or the service, to investigate abuse, to enforce terms, or as part of a merger, acquisition, financing, or transfer of assets.",
    ],
    links: CLOUDFLARE_PRIVACY_REFERENCES,
  },
  {
    title: "7. Retention",
    body: [
      "W7S keeps information for as long as needed to provide the service, comply with legal obligations, resolve disputes, enforce agreements, prevent abuse, and maintain security and reliability.",
      "Deploy artifacts, routing metadata, logs, usage data, and analytics data may have different retention periods. W7S may delete or aggregate older operational data when it is no longer needed.",
    ],
  },
  {
    title: "8. Security",
    body: [
      "W7S uses reasonable safeguards to protect information, including access controls and operational monitoring. No system is perfectly secure, and you are responsible for securing your repositories, workflows, secrets, dependencies, and application code.",
      "If you believe you found a security issue, contact security@w7s.io.",
    ],
  },
  {
    title: "9. International processing",
    body: [
      "W7S and its service providers may process information in countries other than where you live. By using W7S, you understand that information may be processed and stored in those locations, subject to applicable law.",
    ],
  },
  {
    title: "10. Your choices and rights",
    body: [
      "You can stop using hosted W7S services, remove workflow configuration from a repository, rotate or revoke GitHub credentials, remove a custom domain declaration, or request deletion of hosted deployment data where applicable.",
      "Depending on where you live, you may have rights to access, correct, delete, export, or object to certain processing of personal information. Requests can be sent to privacy@w7s.io.",
    ],
  },
  {
    title: "11. Children",
    body: [
      "W7S is intended for developers and organizations. It is not directed to children under 13, and W7S does not knowingly collect personal information from children under 13.",
    ],
  },
  {
    title: "12. Updates and contact",
    body: [
      "W7S may update this Privacy Policy from time to time. The updated date above shows when this page was last changed.",
      "Questions or privacy requests can be sent to privacy@w7s.io.",
    ],
  },
];

const LEGAL_PAGES = {
  terms: {
    title: "Terms of Service",
    eyebrow: "// legal",
    description:
      "The public terms for using W7S websites, hosted deploys, APIs, GitHub Action integrations, and related services.",
    icon: FileText,
    sections: TERMS_SECTIONS,
  },
  privacy: {
    title: "Privacy Policy",
    eyebrow: "// privacy",
    description:
      "How W7S collects, uses, shares, and retains information for the website, docs, hosted deploys, APIs, and GitHub Action integrations.",
    icon: ShieldCheck,
    sections: PRIVACY_SECTIONS,
  },
};

function LegalHeader({ page }) {
  const Icon = page.icon;

  return (
    <header className="border-b border-white/10 bg-[#050505]/95">
      <div className="mx-auto flex min-h-16 max-w-[1400px] flex-col gap-4 px-6 py-5 sm:flex-row sm:items-center sm:justify-between lg:px-10">
        <a href="/" className="flex items-center gap-2">
          <span className="font-display text-2xl tracking-tighter text-white">W7S</span>
          <span className="hidden border border-white/10 px-2 py-1 text-[10px] uppercase tracking-[0.25em] text-zinc-500 sm:inline-block">
            legal
          </span>
        </a>
        <nav className="flex flex-wrap items-center gap-4 text-xs uppercase tracking-[0.2em] text-zinc-400">
          <a href="/" className="hover:text-amber-400 transition-colors">
            Home
          </a>
          <a href="/docs/" className="hover:text-amber-400 transition-colors">
            Docs
          </a>
          <a href="/status" className="hover:text-amber-400 transition-colors">
            Status
          </a>
          <a
            href="https://github.com/w7s-io"
            className="inline-flex items-center gap-1 hover:text-amber-400 transition-colors"
            target="_blank"
            rel="noopener noreferrer"
          >
            GitHub
            <ArrowUpRight className="h-3.5 w-3.5" strokeWidth={2} />
          </a>
        </nav>
      </div>
      <div className="mx-auto max-w-[1400px] px-6 pb-14 pt-10 lg:px-10 lg:pb-20 lg:pt-16">
        <div className="flex items-center gap-3 text-amber-400">
          <Icon className="h-5 w-5" strokeWidth={2} />
          <p className="text-[10px] uppercase tracking-[0.3em]">{page.eyebrow}</p>
        </div>
        <h1 className="mt-5 max-w-4xl font-display text-5xl leading-[0.9] text-white sm:text-6xl lg:text-7xl">
          {page.title}
        </h1>
        <p className="mt-6 max-w-3xl text-sm leading-relaxed text-zinc-400">
          {page.description}
        </p>
        <div className="mt-6 font-mono text-xs uppercase tracking-[0.2em] text-zinc-600">
          Last updated {UPDATED_AT}
        </div>
      </div>
    </header>
  );
}

export default function LegalPage({ type }) {
  const page = LEGAL_PAGES[type] || LEGAL_PAGES.terms;

  useEffect(() => {
    document.title = `W7S ${page.title}`;
  }, [page.title]);

  return (
    <div className="relative z-10 min-h-screen bg-[#050505] text-zinc-100">
      <LegalHeader page={page} />
      <main className="mx-auto max-w-[1100px] px-6 py-14 lg:px-10 lg:py-20">
        <div className="space-y-10">
          {page.sections.map((section) => (
            <section key={section.title} className="border-t border-white/10 pt-8">
              <h2 className="font-display text-2xl text-white sm:text-3xl">
                {section.title}
              </h2>
              <div className="mt-5 space-y-4 text-sm leading-relaxed text-zinc-400">
                {section.body.map((paragraph) => (
                  <p key={paragraph}>{paragraph}</p>
                ))}
                {section.links ? (
                  <ul className="space-y-2 pt-2 font-mono text-xs leading-relaxed">
                    {section.links.map((link) => (
                      <li key={link.href}>
                        <a
                          href={link.href}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="inline-flex items-center gap-1 text-amber-400 underline decoration-amber-400/30 underline-offset-4 transition-colors hover:text-amber-300 hover:decoration-amber-300"
                        >
                          {link.label}
                          <ArrowUpRight className="h-3.5 w-3.5" strokeWidth={2} />
                        </a>
                      </li>
                    ))}
                  </ul>
                ) : null}
              </div>
            </section>
          ))}
        </div>
      </main>
      <Footer />
    </div>
  );
}
